### ISSUE TITLE
Hellfire Council, found spell

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs_WarlordsOfDraenor#10]
![image](https://user-images.githubusercontent.com/16833/43458392-0e04ee0e-94c2-11e8-9503-967598d43c15.png)

**Comment by Xerus2** [comment]
Also seeing this error:
Found spell 'Mark of the Legion' using id 187050 on 16, tell the authors!
BigWigs_Core\BossPrototype.lua:1128: in function `UnitDebuff'
...igs_WarlordsOfDraenor\HellfireCitadel\Archimonde.lua:881: in function `?'
BigWigs_Core\BossPrototype.lua:448: in function <BigWigs_Core\BossPrototype.lua:414>

**Comment by Xerus2** [comment]
1x Found spell 'Mark of the Necromancer' using id 184449 on 16, tell the authors!
BigWigs_Core\BossPrototype.lua:1141: in function `UnitDebuff'
...igWigs_WarlordsOfDraenor\HellfireCitadel\Council.lua:162: in function `?'
BigWigs_Core\BossPrototype.lua:456: in function <BigWigs_Core\BossPrototype.lua:422>

Locals:
InCombatSkipped
