### ISSUE TITLE
Found Spell in Blackrock Foundry Mythic

### ISSUE THREAD

**Issue by Zen-Karma** [BigWigsMods/BigWigs_WarlordsOfDraenor#15]
Got this message while fighting the Heart of the mountain aka Blast Furnace  " Found spell 'Shields Down' using id 158345 on 16, tell the authors!

**Comment by davidcraig** [comment]
Additional spells found

10x Found spell 'Bomb' using id 174716 on 16, tell the authors!
[string "@BigWigs_Core\BossPrototype.lua"]:1159: in function `UnitDebuff'
[string "@BigWigs_WarlordsOfDraenor\BlackrockFoundry\TheBlastFurnace.lua"]:311: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:474: in function <BigWigs_Core\BossPrototype.lua:440>

Locals:
Skipped (In Encounter)


11x Found spell 'Bomb' using id 155192 on 16, tell the authors!
[string "@BigWigs_Core\BossPrototype.lua"]:1159: in function `UnitDebuff'
[string "@BigWigs_WarlordsOfDraenor\BlackrockFoundry\TheBlastFurnace.lua"]:311: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:474: in function <BigWigs_Core\BossPrototype.lua:440>

Locals:
Skipped (In Encounter)
